import type { Customer } from "#lib/types"

export const customers: Customer[] = [
  {
    id: "cust-001",
    name: "Alex Morgan",
    email: "alex@example.com",
    phone: "555-123-4567",
    created_at: "2026-03-14T09:00:00Z",
    order_count: 5,
    total_spent: 829.41,
    addresses: [
      {
        id: "addr-001",
        label: "Home",
        full_name: "Alex Morgan",
        email: "alex@example.com",
        phone: "555-123-4567",
        country: "United States",
        city: "Austin",
        state: "TX",
        zip_code: "78701",
      },
      {
        id: "addr-002",
        label: "Office",
        full_name: "Alex Morgan",
        email: "alex@example.com",
        phone: "555-123-4567",
        country: "United States",
        city: "Round Rock",
        state: "TX",
        zip_code: "78681",
      },
    ],
  },
  {
    id: "cust-002",
    name: "Jordan Lee",
    email: "jordan.lee@example.com",
    phone: "555-234-5678",
    created_at: "2026-04-02T14:30:00Z",
    order_count: 3,
    total_spent: 384.97,
    addresses: [
      {
        id: "addr-003",
        label: "Home",
        full_name: "Jordan Lee",
        email: "jordan.lee@example.com",
        phone: "555-234-5678",
        country: "United States",
        city: "Denver",
        state: "CO",
        zip_code: "80202",
      },
    ],
  },
  {
    id: "cust-003",
    name: "Sam Rivera",
    email: "sam.rivera@example.com",
    created_at: "2026-01-21T11:15:00Z",
    order_count: 7,
    total_spent: 1243.5,
    addresses: [
      {
        id: "addr-004",
        label: "Home",
        full_name: "Sam Rivera",
        email: "sam.rivera@example.com",
        phone: "555-345-6789",
        country: "United States",
        city: "Portland",
        state: "OR",
        zip_code: "97201",
      },
    ],
  },
  {
    id: "cust-004",
    name: "Taylor Kim",
    email: "taylor.kim@example.com",
    phone: "555-456-7890",
    created_at: "2026-05-08T16:45:00Z",
    order_count: 2,
    total_spent: 194.98,
    addresses: [
      {
        id: "addr-005",
        label: "Home",
        full_name: "Taylor Kim",
        email: "taylor.kim@example.com",
        phone: "555-456-7890",
        country: "Canada",
        city: "Vancouver",
        state: "BC",
        zip_code: "V6B 1A1",
      },
    ],
  },
  {
    id: "cust-005",
    name: "Casey Patel",
    email: "casey.patel@example.com",
    created_at: "2025-12-05T08:20:00Z",
    order_count: 9,
    total_spent: 2011.25,
    addresses: [
      {
        id: "addr-006",
        label: "Home",
        full_name: "Casey Patel",
        email: "casey.patel@example.com",
        phone: "555-567-8901",
        country: "United Kingdom",
        city: "London",
        state: "",
        zip_code: "E1 6AN",
      },
    ],
  },
  {
    id: "cust-006",
    name: "Riley Chen",
    email: "riley.chen@example.com",
    phone: "555-678-9012",
    created_at: "2026-06-11T13:00:00Z",
    order_count: 1,
    total_spent: 129.99,
    addresses: [
      {
        id: "addr-007",
        label: "Home",
        full_name: "Riley Chen",
        email: "riley.chen@example.com",
        phone: "555-678-9012",
        country: "United States",
        city: "Seattle",
        state: "WA",
        zip_code: "98101",
      },
    ],
  },
  {
    id: "cust-007",
    name: "Morgan Davis",
    email: "morgan.davis@example.com",
    created_at: "2026-02-17T10:10:00Z",
    order_count: 4,
    total_spent: 567.43,
    addresses: [
      {
        id: "addr-008",
        label: "Home",
        full_name: "Morgan Davis",
        email: "morgan.davis@example.com",
        phone: "555-789-0123",
        country: "Australia",
        city: "Sydney",
        state: "NSW",
        zip_code: "2000",
      },
    ],
  },
  {
    id: "cust-008",
    name: "Avery Brooks",
    email: "avery.brooks@example.com",
    phone: "555-890-1234",
    created_at: "2026-07-01T09:45:00Z",
    order_count: 2,
    total_spent: 248.48,
    addresses: [
      {
        id: "addr-009",
        label: "Home",
        full_name: "Avery Brooks",
        email: "avery.brooks@example.com",
        phone: "555-890-1234",
        country: "United States",
        city: "Chicago",
        state: "IL",
        zip_code: "60601",
      },
    ],
  },
]
