import type { Order } from "#lib/types"

export const orders: Order[] = [
  {
    id: "VG-1041",
    placed_at: "2026-07-28T14:22:00Z",
    status: "delivered",
    item_count: 2,
    subtotal: 154.98,
    shipping: 0,
    discount: 0,
    total: 154.98,
    items: [
      {
        id: "line-1041-1",
        product_id: "prod-006",
        title: "Everyday Crew Tee",
        image_url: "https://picsum.photos/seed/everyday-crew-tee-1/800/800",
        price: 24.99,
        quantity: 1,
        color: "White",
        size: "M",
      },
      {
        id: "line-1041-2",
        product_id: "prod-009",
        title: "Terra Joggers",
        image_url: "https://picsum.photos/seed/terra-joggers-1/800/800",
        price: 44.99,
        quantity: 1,
        color: "Charcoal",
        size: "M",
      },
    ],
    shipping_address: {
      full_name: "Alex Morgan",
      email: "alex@example.com",
      phone: "555-123-4567",
      country: "United States",
      city: "Austin",
      state: "TX",
      zip_code: "78701",
    },
    delivery_estimate: "Delivered Jul 30, 2026",
    timeline: [
      { status: "paid", label: "Order placed", date: "2026-07-28T14:22:00Z", completed: true },
      { status: "processing", label: "Processing", date: "2026-07-28T18:00:00Z", completed: true },
      { status: "shipped", label: "Shipped", date: "2026-07-29T09:15:00Z", completed: true },
      { status: "delivered", label: "Delivered", date: "2026-07-30T11:40:00Z", completed: true },
    ],
  },
  {
    id: "VG-1038",
    placed_at: "2026-07-20T10:05:00Z",
    status: "shipped",
    item_count: 1,
    subtotal: 129.99,
    shipping: 0,
    discount: 0,
    total: 129.99,
    items: [
      {
        id: "line-1038-1",
        product_id: "prod-001",
        title: "Aura Wireless Headphones",
        image_url: "https://picsum.photos/seed/aura-wireless-headphones-1/800/800",
        price: 129.99,
        quantity: 1,
        color: "Black",
      },
    ],
    shipping_address: {
      full_name: "Alex Morgan",
      email: "alex@example.com",
      phone: "555-123-4567",
      country: "United States",
      city: "Austin",
      state: "TX",
      zip_code: "78701",
    },
    delivery_estimate: "Arriving Aug 2, 2026",
    timeline: [
      { status: "paid", label: "Order placed", date: "2026-07-20T10:05:00Z", completed: true },
      { status: "processing", label: "Processing", date: "2026-07-20T16:30:00Z", completed: true },
      { status: "shipped", label: "Shipped", date: "2026-07-22T08:00:00Z", completed: true },
      { status: "delivered", label: "Delivered", date: "", completed: false },
    ],
  },
  {
    id: "VG-1035",
    placed_at: "2026-07-12T09:30:00Z",
    status: "processing",
    item_count: 3,
    subtotal: 219.97,
    shipping: 0,
    discount: 0,
    total: 219.97,
    items: [
      {
        id: "line-1035-1",
        product_id: "prod-010",
        title: "Strider Runner",
        image_url: "https://picsum.photos/seed/strider-runner-1/800/800",
        price: 109.99,
        quantity: 1,
        color: "Cobalt",
        size: "10",
      },
      {
        id: "line-1035-2",
        product_id: "prod-014",
        title: "Heritage Leather Wallet",
        image_url: "https://picsum.photos/seed/heritage-leather-wallet-1/800/800",
        price: 45.0,
        quantity: 1,
        color: "Tan",
      },
      {
        id: "line-1035-3",
        product_id: "prod-016",
        title: "Ember Ceramic Mug Set",
        image_url: "https://picsum.photos/seed/ember-ceramic-mug-set-1/800/800",
        price: 34.99,
        quantity: 2,
        color: "Cream",
      },
    ],
    shipping_address: {
      full_name: "Alex Morgan",
      email: "alex@example.com",
      phone: "555-123-4567",
      country: "United States",
      city: "Austin",
      state: "TX",
      zip_code: "78701",
    },
    delivery_estimate: "Arriving Jul 18, 2026",
    timeline: [
      { status: "paid", label: "Order placed", date: "2026-07-12T09:30:00Z", completed: true },
      { status: "processing", label: "Processing", date: "2026-07-12T14:00:00Z", completed: true },
      { status: "shipped", label: "Shipped", date: "", completed: false },
      { status: "delivered", label: "Delivered", date: "", completed: false },
    ],
  },
  {
    id: "VG-1030",
    placed_at: "2026-06-25T16:45:00Z",
    status: "paid",
    item_count: 1,
    subtotal: 64.99,
    shipping: 0,
    discount: 6.5,
    total: 58.49,
    items: [
      {
        id: "line-1030-1",
        product_id: "prod-017",
        title: "Haven Throw Blanket",
        image_url: "https://picsum.photos/seed/haven-throw-blanket-1/800/800",
        price: 64.99,
        quantity: 1,
        color: "Oatmeal",
      },
    ],
    shipping_address: {
      full_name: "Alex Morgan",
      email: "alex@example.com",
      phone: "555-123-4567",
      country: "United States",
      city: "Austin",
      state: "TX",
      zip_code: "78701",
    },
    delivery_estimate: "Arriving Jul 1, 2026",
    timeline: [
      { status: "paid", label: "Order placed", date: "2026-06-25T16:45:00Z", completed: true },
      { status: "processing", label: "Processing", date: "", completed: false },
      { status: "shipped", label: "Shipped", date: "", completed: false },
      { status: "delivered", label: "Delivered", date: "", completed: false },
    ],
  },
  {
    id: "VG-1025",
    placed_at: "2026-06-10T11:20:00Z",
    status: "delivered",
    item_count: 2,
    subtotal: 259.98,
    shipping: 0,
    discount: 0,
    total: 259.98,
    items: [
      {
        id: "line-1025-1",
        product_id: "prod-002",
        title: "Pulse Smartwatch S2",
        image_url: "https://picsum.photos/seed/pulse-smartwatch-s2-1/800/800",
        price: 199.0,
        quantity: 1,
        color: "Black",
        size: "42mm",
      },
      {
        id: "line-1025-2",
        product_id: "prod-013",
        title: "Canvas Utility Tote",
        image_url: "https://picsum.photos/seed/canvas-utility-tote-1/800/800",
        price: 59.99,
        quantity: 1,
        color: "Tan",
      },
    ],
    shipping_address: {
      full_name: "Alex Morgan",
      email: "alex@example.com",
      phone: "555-123-4567",
      country: "United States",
      city: "Austin",
      state: "TX",
      zip_code: "78701",
    },
    delivery_estimate: "Delivered Jun 14, 2026",
    timeline: [
      { status: "paid", label: "Order placed", date: "2026-06-10T11:20:00Z", completed: true },
      { status: "processing", label: "Processing", date: "2026-06-10T15:00:00Z", completed: true },
      { status: "shipped", label: "Shipped", date: "2026-06-11T10:30:00Z", completed: true },
      { status: "delivered", label: "Delivered", date: "2026-06-14T14:00:00Z", completed: true },
    ],
  },
]
