import type { Product } from "#lib/types"

const img = (seed: string, alt: string, sort_order: number): Product["images"][number] => ({
  id: `img-${seed}`,
  url: `https://picsum.photos/seed/${seed}/800/800`,
  alt,
  is_primary: sort_order === 0,
  sort_order,
})

export const products: Product[] = [
  {
    id: "prod-001",
    slug: "aura-wireless-headphones",
    title: "Aura Wireless Headphones",
    short_description: "Over-ear headphones with active noise cancellation and 40-hour battery.",
    description:
      "The Aura Wireless Headphones pair custom 40mm drivers with hybrid active noise cancellation for an immersive listen anywhere. Memory-foam earcups stay comfortable through long sessions, and a single charge delivers up to 40 hours of playback. Multipoint Bluetooth keeps you connected to laptop and phone at once.",
    brand: "Sonara",
    category_id: "cat-electronics",
    product_type: "Audio",
    price: 129.99,
    compare_at_price: 179.99,
    discount_percent: 28,
    currency: "USD",
    is_featured: true,
    is_published: true,
    sku: "SON-AURA-BLK",
    stock_status: "in_stock",
    rating_average: 4.6,
    rating_count: 128,
    images: [
      img("aura-wireless-headphones-1", "Aura Wireless Headphones in black, side profile", 0),
      img("aura-wireless-headphones-2", "Aura Wireless Headphones earcup detail", 1),
      img("aura-wireless-headphones-3", "Aura Wireless Headphones folded flat", 2),
    ],
    variants: [
      { id: "var-001-blk", color: "Black", sku: "SON-AURA-BLK", stock_status: "in_stock" },
      { id: "var-001-wht", color: "White", sku: "SON-AURA-WHT", stock_status: "in_stock" },
      { id: "var-001-nvy", color: "Navy", sku: "SON-AURA-NVY", stock_status: "low_stock" },
    ],
    colors: ["Black", "White", "Navy"],
    sizes: [],
    tags: ["audio", "anc", "bluetooth"],
    created_at: "2025-11-02T10:00:00Z",
    updated_at: "2026-06-18T14:22:00Z",
    published_at: "2025-11-05T09:00:00Z",
  },
  {
    id: "prod-002",
    slug: "pulse-smartwatch-s2",
    title: "Pulse Smartwatch S2",
    short_description: "AMOLED smartwatch with GPS, heart-rate, and sleep tracking.",
    description:
      "The Pulse S2 keeps training and notifications on your wrist with a bright 1.4-inch AMOLED display, dual-band GPS, and continuous heart-rate monitoring. Sleep staging and recovery scores help you plan the week, while the 10-day battery means fewer charges.",
    brand: "KoreTech",
    category_id: "cat-electronics",
    product_type: "Wearables",
    price: 199.0,
    currency: "USD",
    is_featured: true,
    is_published: true,
    sku: "KOR-PULSE-38-BLK",
    stock_status: "in_stock",
    rating_average: 4.4,
    rating_count: 86,
    images: [
      img("pulse-smartwatch-s2-1", "Pulse Smartwatch S2 showing watch face", 0),
      img("pulse-smartwatch-s2-2", "Pulse Smartwatch S2 side buttons", 1),
      img("pulse-smartwatch-s2-3", "Pulse Smartwatch S2 on wrist", 2),
    ],
    variants: [
      { id: "var-002-38-blk", color: "Black", size: "38mm", sku: "KOR-PULSE-38-BLK", stock_status: "in_stock" },
      { id: "var-002-42-blk", color: "Black", size: "42mm", sku: "KOR-PULSE-42-BLK", price: 219.0, stock_status: "in_stock" },
      { id: "var-002-42-slv", color: "Silver", size: "42mm", sku: "KOR-PULSE-42-SLV", price: 219.0, stock_status: "low_stock" },
    ],
    colors: ["Black", "Silver"],
    sizes: ["38mm", "42mm"],
    tags: ["wearable", "gps", "fitness"],
    created_at: "2025-12-10T08:30:00Z",
    updated_at: "2026-05-30T11:10:00Z",
    published_at: "2025-12-12T09:00:00Z",
  },
  {
    id: "prod-003",
    slug: "volt-20k-power-bank",
    title: "Volt 20K Power Bank",
    short_description: "20,000mAh USB-C power bank with 30W fast charging.",
    description:
      "The Volt 20K keeps phones, tablets, and handheld consoles topped up with 30W USB-C Power Delivery. A slim aluminum shell slips into a jacket pocket, and the LED readout shows exactly how much charge remains.",
    brand: "KoreTech",
    category_id: "cat-electronics",
    product_type: "Charging",
    price: 49.99,
    compare_at_price: 69.99,
    discount_percent: 29,
    currency: "USD",
    is_featured: false,
    is_published: true,
    sku: "KOR-VOLT-20K-GRY",
    stock_status: "low_stock",
    rating_average: 4.2,
    rating_count: 54,
    images: [
      img("volt-20k-power-bank-1", "Volt 20K Power Bank front", 0),
      img("volt-20k-power-bank-2", "Volt 20K Power Bank USB-C port", 1),
      img("volt-20k-power-bank-3", "Volt 20K Power Bank in hand", 2),
    ],
    variants: [
      { id: "var-003-gry", color: "Graphite", sku: "KOR-VOLT-20K-GRY", stock_status: "low_stock" },
      { id: "var-003-slv", color: "Silver", sku: "KOR-VOLT-20K-SLV", stock_status: "in_stock" },
    ],
    colors: ["Graphite", "Silver"],
    sizes: [],
    tags: ["charging", "travel"],
    created_at: "2026-01-08T12:00:00Z",
    updated_at: "2026-06-02T09:45:00Z",
    published_at: "2026-01-10T09:00:00Z",
  },
  {
    id: "prod-004",
    slug: "lumen-led-desk-lamp",
    title: "Lumen LED Desk Lamp",
    short_description: "Dimmable desk lamp with adjustable color temperature.",
    description:
      "The Lumen Desk Lamp tunes from warm 2700K to cool 6000K light so your desk matches the task. A fold-flat arm, touch dimmer, and USB-C charging port keep the footprint small and the utility high.",
    brand: "Brighthaus",
    category_id: "cat-electronics",
    product_type: "Lighting",
    price: 39.99,
    currency: "USD",
    is_featured: false,
    is_published: true,
    sku: "BRT-LUMEN-WHT",
    stock_status: "in_stock",
    rating_average: 4.8,
    rating_count: 210,
    images: [
      img("lumen-led-desk-lamp-1", "Lumen LED Desk Lamp lit on a desk", 0),
      img("lumen-led-desk-lamp-2", "Lumen LED Desk Lamp hinge detail", 1),
      img("lumen-led-desk-lamp-3", "Lumen LED Desk Lamp folded flat", 2),
    ],
    variants: [
      { id: "var-004-wht", color: "White", sku: "BRT-LUMEN-WHT", stock_status: "in_stock" },
      { id: "var-004-blk", color: "Black", sku: "BRT-LUMEN-BLK", stock_status: "in_stock" },
    ],
    colors: ["White", "Black"],
    sizes: [],
    tags: ["home-office", "lighting"],
    created_at: "2025-10-20T15:00:00Z",
    updated_at: "2026-04-22T10:05:00Z",
    published_at: "2025-10-24T09:00:00Z",
  },
  {
    id: "prod-005",
    slug: "orbit-bluetooth-speaker",
    title: "Orbit Bluetooth Speaker",
    short_description: "Compact 360-degree speaker with 20-hour battery.",
    description:
      "The Orbit fills a room with 360-degree sound from a body the size of a water bottle. IPX7 waterproofing shrugs off pool days, and two Orbits can pair for true stereo.",
    brand: "Sonara",
    category_id: "cat-electronics",
    product_type: "Audio",
    price: 79.99,
    currency: "USD",
    is_featured: false,
    is_published: true,
    sku: "SON-ORBIT-SGE",
    stock_status: "out_of_stock",
    rating_average: 4.1,
    rating_count: 43,
    images: [
      img("orbit-bluetooth-speaker-1", "Orbit Bluetooth Speaker on a shelf", 0),
      img("orbit-bluetooth-speaker-2", "Orbit Bluetooth Speaker fabric mesh", 1),
      img("orbit-bluetooth-speaker-3", "Orbit Bluetooth Speaker poolside", 2),
    ],
    variants: [
      { id: "var-005-sge", color: "Sage", sku: "SON-ORBIT-SGE", stock_status: "out_of_stock" },
      { id: "var-005-chr", color: "Charcoal", sku: "SON-ORBIT-CHR", stock_status: "out_of_stock" },
    ],
    colors: ["Sage", "Charcoal"],
    sizes: [],
    tags: ["audio", "outdoor"],
    created_at: "2025-09-14T09:00:00Z",
    updated_at: "2026-03-11T16:40:00Z",
    published_at: "2025-09-18T09:00:00Z",
  },
  {
    id: "prod-006",
    slug: "everyday-crew-tee",
    title: "Everyday Crew Tee",
    short_description: "Heavyweight organic cotton tee with a boxy fit.",
    description:
      "Cut from 220gsm organic cotton, the Everyday Crew Tee holds its shape wash after wash. The boxy, slightly cropped fit layers cleanly under jackets or stands alone.",
    brand: "Northline",
    category_id: "cat-apparel",
    product_type: "T-Shirts",
    price: 24.99,
    currency: "USD",
    is_featured: true,
    is_published: true,
    sku: "NOR-TEE-WHT-M",
    stock_status: "in_stock",
    rating_average: 4.7,
    rating_count: 312,
    images: [
      img("everyday-crew-tee-1", "Everyday Crew Tee in white on hanger", 0),
      img("everyday-crew-tee-2", "Everyday Crew Tee fabric close-up", 1),
      img("everyday-crew-tee-3", "Everyday Crew Tee worn", 2),
    ],
    variants: [
      { id: "var-006-wht-m", color: "White", size: "M", sku: "NOR-TEE-WHT-M", stock_status: "in_stock" },
      { id: "var-006-blk-m", color: "Black", size: "M", sku: "NOR-TEE-BLK-M", stock_status: "in_stock" },
      { id: "var-006-olv-l", color: "Olive", size: "L", sku: "NOR-TEE-OLV-L", stock_status: "low_stock" },
    ],
    colors: ["White", "Black", "Olive", "Heather Grey"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    tags: ["basics", "cotton"],
    created_at: "2025-08-05T11:00:00Z",
    updated_at: "2026-06-25T08:20:00Z",
    published_at: "2025-08-08T09:00:00Z",
  },
  {
    id: "prod-007",
    slug: "atlas-denim-jacket",
    title: "Atlas Denim Jacket",
    short_description: "Classic trucker jacket in rinsed Japanese denim.",
    description:
      "The Atlas is a modern take on the Type III trucker, sewn from 13oz rinsed Japanese denim. Brass shanks, a tailored body, and room for a hoodie underneath make it a three-season staple.",
    brand: "Northline",
    category_id: "cat-apparel",
    product_type: "Jackets",
    price: 89.99,
    compare_at_price: 119.99,
    discount_percent: 25,
    currency: "USD",
    is_featured: true,
    is_published: true,
    sku: "NOR-ATLAS-IND-M",
    stock_status: "in_stock",
    rating_average: 4.5,
    rating_count: 97,
    images: [
      img("atlas-denim-jacket-1", "Atlas Denim Jacket front", 0),
      img("atlas-denim-jacket-2", "Atlas Denim Jacket brass button detail", 1),
      img("atlas-denim-jacket-3", "Atlas Denim Jacket back view", 2),
    ],
    variants: [
      { id: "var-007-ind-m", color: "Indigo", size: "M", sku: "NOR-ATLAS-IND-M", stock_status: "in_stock" },
      { id: "var-007-ind-l", color: "Indigo", size: "L", sku: "NOR-ATLAS-IND-L", stock_status: "in_stock" },
      { id: "var-007-blk-m", color: "Black", size: "M", sku: "NOR-ATLAS-BLK-M", stock_status: "low_stock" },
    ],
    colors: ["Indigo", "Black"],
    sizes: ["S", "M", "L", "XL"],
    tags: ["denim", "outerwear"],
    created_at: "2025-09-28T10:30:00Z",
    updated_at: "2026-05-14T13:55:00Z",
    published_at: "2025-10-01T09:00:00Z",
  },
  {
    id: "prod-008",
    slug: "ridge-flannel-shirt",
    title: "Ridge Flannel Shirt",
    short_description: "Brushed cotton flannel in a classic buffalo check.",
    description:
      "The Ridge Flannel is brushed inside and out for softness, with a tailored body that avoids the boxy flannel look. Corozo buttons and double-needle stitching hold up to years of wear.",
    brand: "Fieldwood",
    category_id: "cat-apparel",
    product_type: "Shirts",
    price: 54.99,
    currency: "USD",
    is_featured: false,
    is_published: true,
    sku: "FLD-RIDGE-RED-M",
    stock_status: "low_stock",
    rating_average: 4.3,
    rating_count: 61,
    images: [
      img("ridge-flannel-shirt-1", "Ridge Flannel Shirt in red check", 0),
      img("ridge-flannel-shirt-2", "Ridge Flannel Shirt cuff detail", 1),
      img("ridge-flannel-shirt-3", "Ridge Flannel Shirt worn outdoors", 2),
    ],
    variants: [
      { id: "var-008-red-m", color: "Red Check", size: "M", sku: "FLD-RIDGE-RED-M", stock_status: "low_stock" },
      { id: "var-008-grn-m", color: "Forest Check", size: "M", sku: "FLD-RIDGE-GRN-M", stock_status: "in_stock" },
    ],
    colors: ["Red Check", "Forest Check"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tags: ["flannel", "fall"],
    created_at: "2025-10-11T09:45:00Z",
    updated_at: "2026-02-19T12:30:00Z",
    published_at: "2025-10-14T09:00:00Z",
  },
  {
    id: "prod-009",
    slug: "terra-joggers",
    title: "Terra Joggers",
    short_description: "Four-way stretch joggers with zip pockets.",
    description:
      "The Terra Jogger moves from couch to trail with four-way stretch fabric, a gusseted crotch, and secure zip pockets. A tapered leg keeps the silhouette clean.",
    brand: "Northline",
    category_id: "cat-apparel",
    product_type: "Pants",
    price: 44.99,
    currency: "USD",
    is_featured: false,
    is_published: true,
    sku: "NOR-TERRA-CHR-M",
    stock_status: "in_stock",
    rating_average: 4.6,
    rating_count: 145,
    images: [
      img("terra-joggers-1", "Terra Joggers in charcoal", 0),
      img("terra-joggers-2", "Terra Joggers zip pocket detail", 1),
      img("terra-joggers-3", "Terra Joggers ankle cuff", 2),
    ],
    variants: [
      { id: "var-009-chr-m", color: "Charcoal", size: "M", sku: "NOR-TERRA-CHR-M", stock_status: "in_stock" },
      { id: "var-009-khk-l", color: "Khaki", size: "L", sku: "NOR-TERRA-KHK-L", stock_status: "in_stock" },
    ],
    colors: ["Charcoal", "Khaki"],
    sizes: ["S", "M", "L", "XL"],
    tags: ["athleisure", "stretch"],
    created_at: "2025-12-01T14:00:00Z",
    updated_at: "2026-06-08T09:15:00Z",
    published_at: "2025-12-04T09:00:00Z",
  },
  {
    id: "prod-010",
    slug: "strider-runner",
    title: "Strider Runner",
    short_description: "Lightweight daily trainer with responsive foam.",
    description:
      "The Strider is a do-everything daily trainer: a nitrogen-infused midsole for pop, a breathable engineered mesh upper, and a rocker geometry that keeps miles feeling easy.",
    brand: "Vael",
    category_id: "cat-footwear",
    product_type: "Running",
    price: 109.99,
    currency: "USD",
    is_featured: true,
    is_published: true,
    sku: "VAL-STRIDER-BLU-10",
    stock_status: "in_stock",
    rating_average: 4.8,
    rating_count: 204,
    images: [
      img("strider-runner-1", "Strider Runner in blue, lateral view", 0),
      img("strider-runner-2", "Strider Runner sole detail", 1),
      img("strider-runner-3", "Strider Runner on a run", 2),
    ],
    variants: [
      { id: "var-010-blu-10", color: "Cobalt", size: "10", sku: "VAL-STRIDER-BLU-10", stock_status: "in_stock" },
      { id: "var-010-blk-10", color: "Black", size: "10", sku: "VAL-STRIDER-BLK-10", stock_status: "in_stock" },
      { id: "var-010-blu-11", color: "Cobalt", size: "11", sku: "VAL-STRIDER-BLU-11", stock_status: "low_stock" },
    ],
    colors: ["Cobalt", "Black", "Stone"],
    sizes: ["7", "8", "9", "10", "11", "12", "13"],
    tags: ["running", "training"],
    created_at: "2026-01-20T10:00:00Z",
    updated_at: "2026-06-30T15:45:00Z",
    published_at: "2026-01-23T09:00:00Z",
  },
  {
    id: "prod-011",
    slug: "court-classic-sneaker",
    title: "Court Classic Sneaker",
    short_description: "Minimal leather sneaker on a cupsole.",
    description:
      "A clean court silhouette in full-grain leather with a cushioned OrthoLite insole. The Court Classic pairs with everything from denim to tailoring.",
    brand: "Vael",
    category_id: "cat-footwear",
    product_type: "Sneakers",
    price: 74.99,
    compare_at_price: 94.99,
    discount_percent: 21,
    currency: "USD",
    is_featured: false,
    is_published: true,
    sku: "VAL-COURT-WHT-9",
    stock_status: "in_stock",
    rating_average: 4.4,
    rating_count: 168,
    images: [
      img("court-classic-sneaker-1", "Court Classic Sneaker in white", 0),
      img("court-classic-sneaker-2", "Court Classic Sneaker heel detail", 1),
      img("court-classic-sneaker-3", "Court Classic Sneaker pair", 2),
    ],
    variants: [
      { id: "var-011-wht-9", color: "White", size: "9", sku: "VAL-COURT-WHT-9", stock_status: "in_stock" },
      { id: "var-011-bne-9", color: "Bone", size: "9", sku: "VAL-COURT-BNE-9", stock_status: "in_stock" },
    ],
    colors: ["White", "Bone"],
    sizes: ["7", "8", "9", "10", "11", "12"],
    tags: ["leather", "minimal"],
    created_at: "2025-11-15T09:30:00Z",
    updated_at: "2026-05-02T11:25:00Z",
    published_at: "2025-11-18T09:00:00Z",
  },
  {
    id: "prod-012",
    slug: "summit-trail-boot",
    title: "Summit Trail Boot",
    short_description: "Waterproof mid boot with Vibram outsole.",
    description:
      "The Summit Trail Boot pairs a waterproof nubuck upper with a grippy Vibram Megagrip outsole. A cushioned EVA midsole and padded collar keep long hikes comfortable.",
    brand: "Fieldwood",
    category_id: "cat-footwear",
    product_type: "Boots",
    price: 139.99,
    currency: "USD",
    is_featured: false,
    is_published: true,
    sku: "FLD-SUMMIT-BRN-10",
    stock_status: "low_stock",
    rating_average: 4.7,
    rating_count: 89,
    images: [
      img("summit-trail-boot-1", "Summit Trail Boot in brown", 0),
      img("summit-trail-boot-2", "Summit Trail Boot lug outsole", 1),
      img("summit-trail-boot-3", "Summit Trail Boot on rocky trail", 2),
    ],
    variants: [
      { id: "var-012-brn-10", color: "Brown", size: "10", sku: "FLD-SUMMIT-BRN-10", stock_status: "low_stock" },
      { id: "var-012-blk-10", color: "Black", size: "10", sku: "FLD-SUMMIT-BLK-10", stock_status: "in_stock" },
    ],
    colors: ["Brown", "Black"],
    sizes: ["8", "9", "10", "11", "12", "13"],
    tags: ["hiking", "waterproof"],
    created_at: "2025-09-02T13:15:00Z",
    updated_at: "2026-04-18T10:40:00Z",
    published_at: "2025-09-05T09:00:00Z",
  },
  {
    id: "prod-013",
    slug: "canvas-utility-tote",
    title: "Canvas Utility Tote",
    short_description: "18oz canvas tote with interior laptop sleeve.",
    description:
      "Built from 18oz waxed canvas with full-grain leather handles, the Utility Tote swallows a 16-inch laptop, a change of clothes, and the day's extras. Riveted stress points age beautifully.",
    brand: "Fieldwood",
    category_id: "cat-accessories",
    product_type: "Bags",
    price: 59.99,
    currency: "USD",
    is_featured: true,
    is_published: true,
    sku: "FLD-TOTE-TAN",
    stock_status: "in_stock",
    rating_average: 4.5,
    rating_count: 73,
    images: [
      img("canvas-utility-tote-1", "Canvas Utility Tote in tan", 0),
      img("canvas-utility-tote-2", "Canvas Utility Tote interior sleeve", 1),
      img("canvas-utility-tote-3", "Canvas Utility Tote leather handle detail", 2),
    ],
    variants: [
      { id: "var-013-tan", color: "Tan", sku: "FLD-TOTE-TAN", stock_status: "in_stock" },
      { id: "var-013-olv", color: "Olive", sku: "FLD-TOTE-OLV", stock_status: "in_stock" },
    ],
    colors: ["Tan", "Olive"],
    sizes: [],
    tags: ["carry", "canvas"],
    created_at: "2025-10-25T16:00:00Z",
    updated_at: "2026-06-12T09:30:00Z",
    published_at: "2025-10-28T09:00:00Z",
  },
  {
    id: "prod-014",
    slug: "heritage-leather-wallet",
    title: "Heritage Leather Wallet",
    short_description: "Slim bifold in vegetable-tanned leather.",
    description:
      "The Heritage Bifold carries six cards and folded bills in a slim vegetable-tanned leather body that darkens with use. RFID shielding is sandwiched invisibly between the panels.",
    brand: "Alder & Co",
    category_id: "cat-accessories",
    product_type: "Wallets",
    price: 45.0,
    currency: "USD",
    is_featured: false,
    is_published: true,
    sku: "ALD-WALLET-TAN",
    stock_status: "in_stock",
    rating_average: 4.9,
    rating_count: 256,
    images: [
      img("heritage-leather-wallet-1", "Heritage Leather Wallet closed", 0),
      img("heritage-leather-wallet-2", "Heritage Leather Wallet open with cards", 1),
      img("heritage-leather-wallet-3", "Heritage Leather Wallet stitching detail", 2),
    ],
    variants: [
      { id: "var-014-tan", color: "Tan", sku: "ALD-WALLET-TAN", stock_status: "in_stock" },
      { id: "var-014-blk", color: "Black", sku: "ALD-WALLET-BLK", stock_status: "in_stock" },
    ],
    colors: ["Tan", "Black"],
    sizes: [],
    tags: ["leather", "edc"],
    created_at: "2025-07-19T10:45:00Z",
    updated_at: "2026-05-27T14:10:00Z",
    published_at: "2025-07-22T09:00:00Z",
  },
  {
    id: "prod-015",
    slug: "drift-chrono-watch",
    title: "Drift Chrono Watch",
    short_description: "40mm chronograph with sapphire crystal.",
    description:
      "The Drift Chrono pairs a brushed 40mm steel case with a domed sapphire crystal and a Japanese quartz chronograph movement. Quick-release straps swap in seconds.",
    brand: "Alder & Co",
    category_id: "cat-accessories",
    product_type: "Watches",
    price: 149.99,
    compare_at_price: 189.99,
    discount_percent: 21,
    currency: "USD",
    is_featured: false,
    is_published: true,
    sku: "ALD-DRIFT-SLV",
    stock_status: "out_of_stock",
    rating_average: 4.6,
    rating_count: 51,
    images: [
      img("drift-chrono-watch-1", "Drift Chrono Watch dial", 0),
      img("drift-chrono-watch-2", "Drift Chrono Watch case profile", 1),
      img("drift-chrono-watch-3", "Drift Chrono Watch on wrist", 2),
    ],
    variants: [
      { id: "var-015-slv", color: "Silver", sku: "ALD-DRIFT-SLV", stock_status: "out_of_stock" },
      { id: "var-015-gld", color: "Gold", sku: "ALD-DRIFT-GLD", stock_status: "out_of_stock" },
    ],
    colors: ["Silver", "Gold"],
    sizes: [],
    tags: ["watches", "chrono"],
    created_at: "2025-11-30T09:00:00Z",
    updated_at: "2026-03-22T17:20:00Z",
    published_at: "2025-12-03T09:00:00Z",
  },
  {
    id: "prod-016",
    slug: "ember-ceramic-mug-set",
    title: "Ember Ceramic Mug Set",
    short_description: "Set of four hand-glazed stoneware mugs.",
    description:
      "Each Ember mug is hand-glazed, so no two are exactly alike. The 12oz stoneware body keeps coffee hot, and the set of four stacks neatly in the cupboard.",
    brand: "Brighthaus",
    category_id: "cat-home-living",
    product_type: "Kitchen",
    price: 34.99,
    currency: "USD",
    is_featured: false,
    is_published: true,
    sku: "BRT-EMBER-SET4",
    stock_status: "in_stock",
    rating_average: 4.7,
    rating_count: 134,
    images: [
      img("ember-ceramic-mug-set-1", "Ember Ceramic Mug Set of four", 0),
      img("ember-ceramic-mug-set-2", "Ember mug glaze detail", 1),
      img("ember-ceramic-mug-set-3", "Ember mug with coffee", 2),
    ],
    variants: [
      { id: "var-016-crm", color: "Cream", sku: "BRT-EMBER-CRM", stock_status: "in_stock" },
      { id: "var-016-ter", color: "Terracotta", sku: "BRT-EMBER-TER", stock_status: "in_stock" },
    ],
    colors: ["Cream", "Terracotta"],
    sizes: [],
    tags: ["kitchen", "stoneware"],
    created_at: "2025-12-18T11:30:00Z",
    updated_at: "2026-06-05T10:00:00Z",
    published_at: "2025-12-21T09:00:00Z",
  },
  {
    id: "prod-017",
    slug: "haven-throw-blanket",
    title: "Haven Throw Blanket",
    short_description: "Chunky-knit throw in recycled wool blend.",
    description:
      "The Haven Throw is a chunky-knit blanket in a recycled wool blend that is equal parts warm and breathable. The 50-by-60 inch size covers one person perfectly or dresses the foot of a bed.",
    brand: "Brighthaus",
    category_id: "cat-home-living",
    product_type: "Bedding",
    price: 64.99,
    compare_at_price: 84.99,
    discount_percent: 24,
    currency: "USD",
    is_featured: true,
    is_published: true,
    sku: "BRT-HAVEN-OAT",
    stock_status: "in_stock",
    rating_average: 4.8,
    rating_count: 187,
    images: [
      img("haven-throw-blanket-1", "Haven Throw Blanket draped on sofa", 0),
      img("haven-throw-blanket-2", "Haven Throw Blanket knit texture", 1),
      img("haven-throw-blanket-3", "Haven Throw Blanket folded", 2),
    ],
    variants: [
      { id: "var-017-oat", color: "Oatmeal", sku: "BRT-HAVEN-OAT", stock_status: "in_stock" },
      { id: "var-017-slt", color: "Slate", sku: "BRT-HAVEN-SLT", stock_status: "in_stock" },
    ],
    colors: ["Oatmeal", "Slate"],
    sizes: [],
    tags: ["cozy", "wool"],
    created_at: "2025-10-07T09:15:00Z",
    updated_at: "2026-05-19T12:50:00Z",
    published_at: "2025-10-10T09:00:00Z",
  },
  {
    id: "prod-018",
    slug: "nimbus-scented-candle",
    title: "Nimbus Scented Candle",
    short_description: "Cedar and amber soy candle, 55-hour burn.",
    description:
      "Nimbus blends cedar, amber, and a whisper of smoke in a clean-burning soy wax candle. The 8oz glass vessel burns for roughly 55 hours and reuses as a catchall.",
    brand: "Alder & Co",
    category_id: "cat-home-living",
    product_type: "Home Fragrance",
    price: 22.99,
    currency: "USD",
    is_featured: false,
    is_published: true,
    sku: "ALD-NIMBUS-CDR",
    stock_status: "low_stock",
    rating_average: 4.2,
    rating_count: 66,
    images: [
      img("nimbus-scented-candle-1", "Nimbus Scented Candle lit", 0),
      img("nimbus-scented-candle-2", "Nimbus candle label detail", 1),
      img("nimbus-scented-candle-3", "Nimbus candle on nightstand", 2),
    ],
    variants: [
      { id: "var-018-cdr", color: "Cedar & Amber", sku: "ALD-NIMBUS-CDR", stock_status: "low_stock" },
      { id: "var-018-fig", color: "Fig & Vetiver", sku: "ALD-NIMBUS-FIG", stock_status: "in_stock" },
    ],
    colors: ["Cedar & Amber", "Fig & Vetiver"],
    sizes: [],
    tags: ["candle", "gift"],
    created_at: "2026-01-05T10:20:00Z",
    updated_at: "2026-06-20T08:35:00Z",
    published_at: "2026-01-08T09:00:00Z",
  },
]
