import type { Review } from "#lib/types"

export const reviews: Review[] = [
  // prod-001 Aura Wireless Headphones
  {
    id: "rev-001-1",
    product_id: "prod-001",
    author_name: "Maya R.",
    rating: 5,
    title: "Best ANC under $150",
    body: "The noise cancellation rivals my old pair that cost twice as much. Battery easily lasts a full work week.",
    created_at: "2026-05-28T09:12:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-001-2",
    product_id: "prod-001",
    author_name: "Devon K.",
    rating: 4,
    title: "Great sound, slightly tight fit",
    body: "Sound signature is warm and detailed. The clamp force was tight for the first week but it loosened up nicely.",
    created_at: "2026-04-15T16:40:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-001-3",
    product_id: "prod-001",
    author_name: "Priya S.",
    rating: 5,
    body: "Multipoint works flawlessly between my laptop and phone. Switching is instant and I have had zero dropouts.",
    created_at: "2026-03-02T11:05:00Z",
  },
  // prod-002 Pulse Smartwatch S2
  {
    id: "rev-002-1",
    product_id: "prod-002",
    author_name: "Tom H.",
    rating: 4,
    title: "Solid training companion",
    body: "GPS locks fast and the recovery scores are genuinely useful for planning rest days. Wish the strap were softer.",
    created_at: "2026-06-10T08:30:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-002-2",
    product_id: "prod-002",
    author_name: "Alina W.",
    rating: 5,
    title: "Battery for days",
    body: "Ten days between charges with always-on display off. The AMOLED screen is readable in direct sunlight.",
    created_at: "2026-05-11T19:22:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-002-3",
    product_id: "prod-002",
    author_name: "Marcus B.",
    rating: 4,
    body: "Sleep staging matches my other tracker closely. Notifications are legible and easy to dismiss.",
    created_at: "2026-02-24T14:15:00Z",
  },
  // prod-003 Volt 20K Power Bank
  {
    id: "rev-003-1",
    product_id: "prod-003",
    author_name: "Jess L.",
    rating: 4,
    title: "Reliable travel brick",
    body: "Charged my phone four times on one trip and still had 30% left. The percentage display is more useful than dots.",
    created_at: "2026-06-01T10:48:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-003-2",
    product_id: "prod-003",
    author_name: "Owen D.",
    rating: 5,
    body: "30W output actually fast-charges my tablet. Slim enough to forget it is in my jacket pocket.",
    created_at: "2026-04-19T13:33:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-003-3",
    product_id: "prod-003",
    author_name: "Hana Y.",
    rating: 4,
    body: "Slightly heavier than expected for the size, but the aluminum shell feels like it will survive drops.",
    created_at: "2026-01-27T09:58:00Z",
  },
  // prod-004 Lumen LED Desk Lamp
  {
    id: "rev-004-1",
    product_id: "prod-004",
    author_name: "Ravi P.",
    rating: 5,
    title: "Perfect WFH lamp",
    body: "The color temperature range covers morning focus to late-evening reading. The touch dimmer is responsive.",
    created_at: "2026-06-14T20:10:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-004-2",
    product_id: "prod-004",
    author_name: "Sofia M.",
    rating: 5,
    body: "Folds completely flat so I can stash it when guests come over. Build quality exceeds the price.",
    created_at: "2026-03-30T15:27:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-004-3",
    product_id: "prod-004",
    author_name: "Ben C.",
    rating: 4,
    title: "Great, minor wobble",
    body: "Light quality is excellent. The arm wobbles slightly if you bump the desk, but it settles instantly.",
    created_at: "2026-02-08T12:44:00Z",
  },
  // prod-005 Orbit Bluetooth Speaker
  {
    id: "rev-005-1",
    product_id: "prod-005",
    author_name: "Lena F.",
    rating: 4,
    title: "Impressive for the size",
    body: "The 360-degree sound genuinely fills my kitchen. Survived an accidental drop into the sink.",
    created_at: "2026-01-19T18:05:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-005-2",
    product_id: "prod-005",
    author_name: "Kai T.",
    rating: 4,
    body: "Bass is restrained but clean. Stereo pairing with a second unit was painless.",
    created_at: "2025-12-22T09:41:00Z",
  },
  {
    id: "rev-005-3",
    product_id: "prod-005",
    author_name: "Rita G.",
    rating: 4,
    title: "Pool-day proof",
    body: "Used it poolside all summer. Battery got me through two full afternoons per charge.",
    created_at: "2025-11-03T14:56:00Z",
    verified_purchase: true,
  },
  // prod-006 Everyday Crew Tee
  {
    id: "rev-006-1",
    product_id: "prod-006",
    author_name: "Chris N.",
    rating: 5,
    title: "The only tee I buy now",
    body: "Heavyweight without being hot, and the collar has not bacon-necked after a dozen washes.",
    created_at: "2026-06-22T08:14:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-006-2",
    product_id: "prod-006",
    author_name: "Amara O.",
    rating: 5,
    body: "The boxy fit is exactly right with high-waisted jeans. Ordered three more colors.",
    created_at: "2026-05-05T17:38:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-006-3",
    product_id: "prod-006",
    author_name: "Felix J.",
    rating: 4,
    title: "Great, size down if between",
    body: "Quality is superb for the price. I sized down for a less boxy look and it is perfect.",
    created_at: "2026-04-02T10:29:00Z",
  },
  // prod-007 Atlas Denim Jacket
  {
    id: "rev-007-1",
    product_id: "prod-007",
    author_name: "Nora E.",
    rating: 5,
    title: "Wears in beautifully",
    body: "Six months in and the fades at the elbows look fantastic. Roomy enough for a hoodie underneath.",
    created_at: "2026-06-08T13:52:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-007-2",
    product_id: "prod-007",
    author_name: "Isaac V.",
    rating: 4,
    body: "The denim quality punches above the price. Sleeves run slightly long on me.",
    created_at: "2026-03-18T09:36:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-007-3",
    product_id: "prod-007",
    author_name: "Greta U.",
    rating: 4,
    title: "Classic cut, modern fit",
    body: "Tailored without being slim. The brass buttons feel substantial and the stitching is clean.",
    created_at: "2026-01-11T15:19:00Z",
  },
  // prod-008 Ridge Flannel Shirt
  {
    id: "rev-008-1",
    product_id: "prod-008",
    author_name: "Paul M.",
    rating: 4,
    title: "Softest flannel I own",
    body: "Brushed on both sides so it is comfortable against skin. True to size.",
    created_at: "2026-02-14T11:08:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-008-2",
    product_id: "prod-008",
    author_name: "Dana R.",
    rating: 5,
    body: "The forest check colorway is even better in person. Corozo buttons are a nice touch.",
    created_at: "2025-12-05T16:47:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-008-3",
    product_id: "prod-008",
    author_name: "Silas T.",
    rating: 4,
    body: "Warm enough to be a light jacket in fall. Washed twice with no shrinkage.",
    created_at: "2025-11-20T08:55:00Z",
  },
  // prod-009 Terra Joggers
  {
    id: "rev-009-1",
    product_id: "prod-009",
    author_name: "Ivy Z.",
    rating: 5,
    title: "Live in these",
    body: "The stretch fabric handles squats at the gym and still looks sharp for errands. Zip pockets fit a large phone.",
    created_at: "2026-06-19T19:03:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-009-2",
    product_id: "prod-009",
    author_name: "Hugo A.",
    rating: 4,
    body: "Taper is flattering and the waistband stays put. Fabric is quieter than most technical joggers.",
    created_at: "2026-04-27T12:21:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-009-3",
    product_id: "prod-009",
    author_name: "Mona Q.",
    rating: 4,
    title: "Nearly perfect",
    body: "Comfortable all day. Would love a back pocket, but the side zips are secure.",
    created_at: "2026-02-16T14:39:00Z",
  },
  // prod-010 Strider Runner
  {
    id: "rev-010-1",
    product_id: "prod-010",
    author_name: "Eli W.",
    rating: 5,
    title: "My marathon shoe",
    body: "Trained 300 miles in these with zero blisters. The rocker makes long runs feel effortless.",
    created_at: "2026-06-25T06:47:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-010-2",
    product_id: "prod-010",
    author_name: "Tara B.",
    rating: 5,
    body: "The foam is bouncy without being unstable. Breathable enough for summer tempo days.",
    created_at: "2026-05-16T10:12:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-010-3",
    product_id: "prod-010",
    author_name: "Jon F.",
    rating: 4,
    title: "Great daily trainer",
    body: "Runs slightly narrow in the toe box. Half size up fixed it and now they are my go-to.",
    created_at: "2026-03-09T15:58:00Z",
  },
  // prod-011 Court Classic Sneaker
  {
    id: "rev-011-1",
    product_id: "prod-011",
    author_name: "Milo D.",
    rating: 4,
    title: "Clean and versatile",
    body: "The leather is thicker than expected at this price. Minimal branding keeps them office-appropriate.",
    created_at: "2026-05-29T09:26:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-011-2",
    product_id: "prod-011",
    author_name: "June H.",
    rating: 5,
    body: "Broke in after two wears and now they are the most comfortable sneakers I own.",
    created_at: "2026-04-11T18:33:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-011-3",
    product_id: "prod-011",
    author_name: "Reed S.",
    rating: 4,
    body: "The cupsole is firmer than knit sneakers but supportive for all-day city walking.",
    created_at: "2026-01-23T11:45:00Z",
  },
  // prod-012 Summit Trail Boot
  {
    id: "rev-012-1",
    product_id: "prod-012",
    author_name: "Wren K.",
    rating: 5,
    title: "Kept my feet dry in a downpour",
    body: "Hiked 12 miles through rain and stream crossings. Completely dry, and the Vibram grip on wet rock is superb.",
    created_at: "2026-04-21T07:15:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-012-2",
    product_id: "prod-012",
    author_name: "Oscar P.",
    rating: 4,
    body: "Required about 10 miles to break in. Since then, zero hot spots on 15+ mile days.",
    created_at: "2026-02-27T13:44:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-012-3",
    product_id: "prod-012",
    author_name: "Nadia L.",
    rating: 5,
    title: "Supportive without the bulk",
    body: "Ankle support is excellent for the weight. The nubuck has held up to scree better than expected.",
    created_at: "2025-12-30T10:31:00Z",
  },
  // prod-013 Canvas Utility Tote
  {
    id: "rev-013-1",
    product_id: "prod-013",
    author_name: "Bea N.",
    rating: 5,
    title: "My everyday carry",
    body: "Fits my 16-inch laptop, gym clothes, and lunch. The waxed canvas shrugs off rain and looks better scuffed.",
    created_at: "2026-06-03T09:19:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-013-2",
    product_id: "prod-013",
    author_name: "Theo G.",
    rating: 4,
    body: "The leather handles are comfortable even when the bag is loaded heavy. Rivets feel bombproof.",
    created_at: "2026-03-25T14:52:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-013-3",
    product_id: "prod-013",
    author_name: "Lulu C.",
    rating: 4,
    title: "Sturdy and handsome",
    body: "Stands up on its own when set down, which I did not know I needed. Interior sleeve is well padded.",
    created_at: "2026-01-14T16:07:00Z",
  },
  // prod-014 Heritage Leather Wallet
  {
    id: "rev-014-1",
    product_id: "prod-014",
    author_name: "Sam O.",
    rating: 5,
    title: "Ages like a dream",
    body: "Eight months of daily carry and the tan leather has developed a gorgeous patina. Stitching is flawless.",
    created_at: "2026-05-21T11:37:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-014-2",
    product_id: "prod-014",
    author_name: "Freya I.",
    rating: 5,
    body: "Slim enough for a front pocket but still holds six cards and cash. The RFID lining gives peace of mind.",
    created_at: "2026-04-06T08:49:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-014-3",
    product_id: "prod-014",
    author_name: "Abe W.",
    rating: 5,
    title: "Bought a second as a gift",
    body: "Impressed enough to order one for my dad. Card slots were snug for the first week, then perfect.",
    created_at: "2026-02-12T15:28:00Z",
  },
  // prod-015 Drift Chrono Watch
  {
    id: "rev-015-1",
    product_id: "prod-015",
    author_name: "Iris V.",
    rating: 5,
    title: "Looks far more expensive",
    body: "The domed sapphire catches light beautifully. Constant compliments at work.",
    created_at: "2026-03-13T10:05:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-015-2",
    product_id: "prod-015",
    author_name: "Cole R.",
    rating: 4,
    body: "The chrono pushers have a satisfying click. Quick-release straps make it easy to dress up or down.",
    created_at: "2026-01-29T17:41:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-015-3",
    product_id: "prod-015",
    author_name: "Maren D.",
    rating: 4,
    title: "Great daily watch",
    body: "40mm wears well on my smaller wrist. Keeps accurate time as expected from the movement.",
    created_at: "2025-12-19T09:57:00Z",
  },
  // prod-016 Ember Ceramic Mug Set
  {
    id: "rev-016-1",
    product_id: "prod-016",
    author_name: "Jude T.",
    rating: 5,
    title: "Beautiful glaze variation",
    body: "Each mug is slightly different, which makes the set feel artisanal. Great weight in the hand.",
    created_at: "2026-06-17T08:23:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-016-2",
    product_id: "prod-016",
    author_name: "Clara X.",
    rating: 4,
    body: "Keeps coffee hot noticeably longer than my old mugs. Dishwasher safe with no fading so far.",
    created_at: "2026-04-24T13:16:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-016-3",
    product_id: "prod-016",
    author_name: "Ezra B.",
    rating: 5,
    body: "The terracotta colorway is warm and earthy. Guests always ask where they are from.",
    created_at: "2026-02-03T10:54:00Z",
  },
  // prod-017 Haven Throw Blanket
  {
    id: "rev-017-1",
    product_id: "prod-017",
    author_name: "Willa S.",
    rating: 5,
    title: "The perfect couch blanket",
    body: "Chunky knit feels substantial but breathes well. It has survived weekly use and one toddler.",
    created_at: "2026-06-12T19:44:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-017-2",
    product_id: "prod-017",
    author_name: "Noel P.",
    rating: 5,
    body: "The oatmeal color works with everything. No pilling after three months of daily naps.",
    created_at: "2026-03-07T15:33:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-017-3",
    product_id: "prod-017",
    author_name: "Gia F.",
    rating: 4,
    title: "Cozy, slight shedding at first",
    body: "Shed a bit during the first week, then settled. Warmth-to-weight ratio is excellent.",
    created_at: "2026-01-18T12:09:00Z",
  },
  // prod-018 Nimbus Scented Candle
  {
    id: "rev-018-1",
    product_id: "prod-018",
    author_name: "Rhys M.",
    rating: 4,
    title: "Subtle, not cloying",
    body: "The cedar and amber blend reads sophisticated rather than sweet. Even burn with no tunneling.",
    created_at: "2026-05-08T20:17:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-018-2",
    product_id: "prod-018",
    author_name: "Opal J.",
    rating: 5,
    body: "Burned through the first one in a month and immediately reordered. The glass cleans out easily for reuse.",
    created_at: "2026-03-19T09:02:00Z",
    verified_purchase: true,
  },
  {
    id: "rev-018-3",
    product_id: "prod-018",
    author_name: "Vera H.",
    rating: 4,
    body: "Throw is moderate — perfect for a bedroom, maybe light for a large living room.",
    created_at: "2026-02-06T14:38:00Z",
  },
]
